# Copyright (C) 2012 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/lge/msm7x27-common/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/lge/msm7x27-common/proprietary/lib/libdivxdrmdecrypt.so:system/lib/libdivxdrmdecrypt.so \
    vendor/lge/msm7x27-common/proprietary/lib/libgls.so:system/lib/libgls.so \
    vendor/lge/msm7x27-common/proprietary/lib/libmm-abl.so:system/lib/libmm-abl.so \
    vendor/lge/msm7x27-common/proprietary/lib/libmm-adspsvc.so:system/lib/libmm-adspsvc.so \
    vendor/lge/msm7x27-common/proprietary/lib/libmmosal.so:system/lib/libmmosal.so \
    vendor/lge/msm7x27-common/proprietary/lib/libmmparser.so:system/lib/libmmparser.so \
    vendor/lge/msm7x27-common/proprietary/lib/libmmparser_divxdrmlib.so:system/lib/libmmparser_divxdrmlib.so \
    vendor/lge/msm7x27-common/proprietary/lib/libmvs.so:system/lib/libmvs.so \
    vendor/lge/msm7x27-common/proprietary/lib/libnexadaption_layer.so:system/lib/libnexadaption_layer.so \
    vendor/lge/msm7x27-common/proprietary/lib/libnexaudiorenderer.so:system/lib/libnexaudiorenderer.so \
    vendor/lge/msm7x27-common/proprietary/lib/libnexplayersdk.so:system/lib/libnexplayersdk.so \
    vendor/lge/msm7x27-common/proprietary/lib/libnexstreaming_aac_dl.so:system/lib/libnexstreaming_aac_dl.so \
    vendor/lge/msm7x27-common/proprietary/lib/libnexstreaming_amrnb_dl.so:system/lib/libnexstreaming_amrnb_dl.so \
    vendor/lge/msm7x27-common/proprietary/lib/libnexstreaming_amrwb_dl.so:system/lib/libnexstreaming_amrwb_dl.so \
    vendor/lge/msm7x27-common/proprietary/lib/libnexstreaming_asp_dl.so:system/lib/libnexstreaming_asp_dl.so \
    vendor/lge/msm7x27-common/proprietary/lib/libnexstreaming_divx3_dl.so:system/lib/libnexstreaming_divx3_dl.so \
    vendor/lge/msm7x27-common/proprietary/lib/libnexstreaming_divx_drm16_service.so:system/lib/libnexstreaming_divx_drm16_service.so \
    vendor/lge/msm7x27-common/proprietary/lib/libnexstreaming_drm16.so:system/lib/libnexstreaming_drm16.so \
    vendor/lge/msm7x27-common/proprietary/lib/libnexstreaming_h264_dl.so:system/lib/libnexstreaming_h264_dl.so \
    vendor/lge/msm7x27-common/proprietary/lib/libnexstreaming_mp3_dl.so:system/lib/libnexstreaming_mp3_dl.so \
    vendor/lge/msm7x27-common/proprietary/lib/libnexstreaming_pcm_dl.so:system/lib/libnexstreaming_pcm_dl.so \
    vendor/lge/msm7x27-common/proprietary/lib/libnexstreaming_qcom_dl.so:system/lib/libnexstreaming_qcom_dl.so \
    vendor/lge/msm7x27-common/proprietary/lib/libnexstreaming_subtitle_jni.so:system/lib/libnexstreaming_subtitle_jni.so \
    vendor/lge/msm7x27-common/proprietary/lib/libnexstreaming_wma_dl.so:system/lib/libnexstreaming_wma_dl.so \
    vendor/lge/msm7x27-common/proprietary/lib/libnexstreaming_wmv_dl.so:system/lib/libnexstreaming_wmv_dl.so \
    vendor/lge/msm7x27-common/proprietary/lib/libnexvideodisplayer.so:system/lib/libnexvideodisplayer.so \
    vendor/lge/msm7x27-common/proprietary/lib/libOmxAacDec.so:system/lib/libOmxAacDec.so \
    vendor/lge/msm7x27-common/proprietary/lib/libOmxAacEnc.so:system/lib/libOmxAacEnc.so \
    vendor/lge/msm7x27-common/proprietary/lib/libOmxAdpcmDec.so:system/lib/libOmxAdpcmDec.so \
    vendor/lge/msm7x27-common/proprietary/lib/libOmxAmrDec.so:system/lib/libOmxAmrDec.so \
    vendor/lge/msm7x27-common/proprietary/lib/libOmxAmrEnc.so:system/lib/libOmxAmrEnc.so \
    vendor/lge/msm7x27-common/proprietary/lib/libOmxAmrRtpDec.so:system/lib/libOmxAmrRtpDec.so \
    vendor/lge/msm7x27-common/proprietary/lib/libOmxAmrwbDec.so:system/lib/libOmxAmrwbDec.so \
    vendor/lge/msm7x27-common/proprietary/lib/libOmxEvrcEnc.so:system/lib/libOmxEvrcEnc.so \
    vendor/lge/msm7x27-common/proprietary/lib/libOmxEvrcHwDec.so:system/lib/libOmxEvrcHwDec.so \
    vendor/lge/msm7x27-common/proprietary/lib/libOmxH264Dec.so:system/lib/libOmxH264Dec.so \
    vendor/lge/msm7x27-common/proprietary/lib/libOmxMp3Dec.so:system/lib/libOmxMp3Dec.so \
    vendor/lge/msm7x27-common/proprietary/lib/libOmxMpeg4Dec.so:system/lib/libOmxMpeg4Dec.so \
    vendor/lge/msm7x27-common/proprietary/lib/libOmxOn2Dec.so:system/lib/libOmxOn2Dec.so \
    vendor/lge/msm7x27-common/proprietary/lib/libOmxQcelp13Enc.so:system/lib/libOmxQcelp13Enc.so \
    vendor/lge/msm7x27-common/proprietary/lib/libOmxQcelpHwDec.so:system/lib/libOmxQcelpHwDec.so \
    vendor/lge/msm7x27-common/proprietary/lib/libOmxVidEnc.so:system/lib/libOmxVidEnc.so \
    vendor/lge/msm7x27-common/proprietary/lib/libOmxWmaDec.so:system/lib/libOmxWmaDec.so \
    vendor/lge/msm7x27-common/proprietary/lib/libOmxWmvDec.so:system/lib/libOmxWmvDec.so \
